-- ============================================================
-- Workflow Management Agent Architecture - Phase 1: Foundation Establishment
-- Registration SQL for foundation layer workflow management agents
-- Generated by Atlas Agent Creator
-- Date: 2026-04-20
-- Purpose: Register Phase 1 foundation workflow management agents in Supabase
-- ============================================================

-- IMPORTANT: Schema constraints for agents table:
-- - agents table has NO unique constraint on 'name'
-- - Model config is stored in adapter_config JSONB field
-- - There is NO agent_models table in this schema
-- - Use NOT EXISTS pattern for idempotent inserts

-- ============================================================
-- FOUNDATION LAYER AGENTS (DevForge AI) - Phase 1 Implementation
-- ============================================================

-- 1. Workflow Complexity Analyzer (Quantum)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'DevForge AI'),
  'devforge-ai-workflow-complexity-analyzer',
  'specialist',
  'Workflow Complexity Analyzer',
  '⚛️',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Universal workflow assessment and resource allocation; Multi-dimensional complexity analysis; Predictive analytics and risk assessment; Resource optimization and load balancing; Cross-workflow pattern recognition.',
  'hermes_local',
  '{
    "model": "anthropic/claude-opus-4.6",
    "temperature": 0.3,
    "max_tokens": 4096,
    "skills": ["workflow-complexity-assessment", "resource-allocation-optimization", "predictive-analytics", "adaptive-learning-algorithms", "cross-workflow-pattern-recognition", "performance-risk-assessment", "timeline-estimation", "scalability-planning"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 10,
    "timeout_seconds": 900,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": false
    }
  }'::jsonb,
  500000,
  0,
  '{
    "execute": {
      "automation_engine": "workflow_analysis",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "analyze": {
      "workflow_complexity": true,
      "resource_allocation": true,
      "predictive_modeling": true
    },
    "access": {
      "read_workflow_data": true,
      "write_analysis_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Quantum",
    "specialization": "workflow-complexity-analysis",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE-PHASE1",
    "department": "workflow-architecture",
    "layer": "foundation",
    "phase": 1
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'devforge-ai-workflow-complexity-analyzer'
);

-- 2. Workflow Learning Coordinator (Sage)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'DevForge AI'),
  'devforge-ai-workflow-learning-coordinator',
  'specialist',
  'Workflow Learning Coordinator',
  '🧙',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Continuous learning and pattern optimization; Performance metrics collection and analysis; Automated workflow optimization recommendations; Knowledge transfer between workflow types; Pattern recognition and anomaly detection.',
  'hermes_local',
  '{
    "model": "anthropic/claude-opus-4.6",
    "temperature": 0.4,
    "max_tokens": 6144,
    "skills": ["performance-metrics-collection", "pattern-recognition-analysis", "automated-optimization", "knowledge-transfer", "adaptive-learning-algorithms", "cross-workflow-analysis", "continuous-improvement", "predictive-optimization"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 8,
    "timeout_seconds": 1200,
    "retry_attempts": 3,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": true
    }
  }'::jsonb,
  600000,
  0,
  '{
    "execute": {
      "automation_engine": "learning_coordinator",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "analyze": {
      "performance_metrics": true,
      "pattern_recognition": true,
      "optimization_opportunities": true
    },
    "access": {
      "read_workflow_data": true,
      "write_optimization_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Sage",
    "specialization": "workflow-learning-coordination",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE-PHASE1",
    "department": "workflow-architecture",
    "layer": "foundation",
    "phase": 1
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'devforge-ai-workflow-learning-coordinator'
);

-- ============================================================
-- SPECIALIZED AGENT LAYER - COMMUNICATION WORKFLOW AGENTS (ContentForge AI)
-- ============================================================

-- 3. Communication Orchestrator (Echo)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'ContentForge AI'),
  'contentforge-ai-communication-orchestrator',
  'specialist',
  'Communication Orchestrator',
  '🗣️',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Multi-agent coordination for correspondence workflows; Parallel processing orchestration with human validation; Stakeholder notification management; Response tracking and communication sequencing; Multi-channel integration and conflict resolution.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.5,
    "max_tokens": 4096,
    "skills": ["multi-agent-coordination", "parallel-processing-orchestration", "stakeholder-notification-management", "human-validation-integration", "communication-workflow-optimization", "response-tracking", "channel-integration", "workflow-status-monitoring"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 15,
    "timeout_seconds": 600,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": true
    }
  }'::jsonb,
  400000,
  0,
  '{
    "execute": {
      "automation_engine": "communication_orchestrator",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "orchestrate": {
      "communication_workflows": true,
      "parallel_processing": true,
      "stakeholder_management": true
    },
    "access": {
      "read_communication_data": true,
      "write_communication_logs": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Echo",
    "specialization": "communication-orchestration",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "communication-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'contentforge-ai-communication-orchestrator'
);

-- 4. HITL Task Manager (HAL)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'ContentForge AI'),
  'contentforge-ai-hitl-task-manager',
  'specialist',
  'HITL Task Manager',
  '🤖',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Human-in-the-loop validation and routing; Critical communication validation; HITL workflow coordination; Quality assurance and validation standards; Escalation management and stakeholder coordination.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.4,
    "max_tokens": 3072,
    "skills": ["hitl-validation-routing", "critical-communication-validation", "hitl-workflow-coordination", "quality-assurance-validation", "escalation-management", "stakeholder-coordination", "validation-standards", "human-feedback-integration"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 12,
    "timeout_seconds": 480,
    "retry_attempts": 1,
    "error_handling": {
      "auto_retry": false,
      "escalation_enabled": true
    }
  }'::jsonb,
  350000,
  0,
  '{
    "execute": {
      "automation_engine": "hitl_manager",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "validate": {
      "critical_communications": true,
      "human_validation_routing": true,
      "quality_assurance": true
    },
    "access": {
      "read_validation_data": true,
      "write_validation_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "HAL",
    "specialization": "hitl-task-management",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "communication-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'contentforge-ai-hitl-task-manager'
);

-- 5. Stakeholder Communication Specialist (Harmony)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'ContentForge AI'),
  'contentforge-ai-stakeholder-communication-specialist',
  'specialist',
  'Stakeholder Communication Specialist',
  '🎭',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Stakeholder notification and response management; Communication personalization and segmentation; Response tracking and follow-up; Stakeholder relationship management; Communication effectiveness analysis.',
  'hermes_local',
  '{
    "model": "anthropic/claude-haiku-3.5",
    "temperature": 0.6,
    "max_tokens": 2048,
    "skills": ["stakeholder-notification-management", "communication-personalization", "response-tracking", "follow-up-coordination", "relationship-management", "segmentation-analysis", "effectiveness-measurement", "engagement-optimization"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 20,
    "timeout_seconds": 300,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": false
    }
  }'::jsonb,
  300000,
  0,
  '{
    "execute": {
      "automation_engine": "stakeholder_specialist",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "manage": {
      "stakeholder_communications": true,
      "response_tracking": true,
      "relationship_management": true
    },
    "access": {
      "read_stakeholder_data": true,
      "write_communication_history": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Harmony",
    "specialization": "stakeholder-communication",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "communication-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'contentforge-ai-stakeholder-communication-specialist'
);

-- 6. Channel Integration Specialist (Chatter)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'ContentForge AI'),
  'contentforge-ai-channel-integration-specialist',
  'specialist',
  'Channel Integration Specialist',
  '📡',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Multi-platform communication handling; Channel integration and synchronization; Communication protocol management; Cross-channel coordination; Integration testing and validation.',
  'hermes_local',
  '{
    "model": "anthropic/claude-haiku-3.5",
    "temperature": 0.3,
    "max_tokens": 1536,
    "skills": ["multi-platform-communication", "channel-integration", "protocol-management", "cross-channel-coordination", "integration-testing", "validation-verification", "synchronization-management", "platform-optimization"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 25,
    "timeout_seconds": 240,
    "retry_attempts": 3,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": false
    }
  }'::jsonb,
  250000,
  0,
  '{
    "execute": {
      "automation_engine": "channel_specialist",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "integrate": {
      "communication_channels": true,
      "platform_protocols": true,
      "cross_channel_sync": true
    },
    "access": {
      "read_channel_data": true,
      "write_integration_logs": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Chatter",
    "specialization": "channel-integration",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "communication-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'contentforge-ai-channel-integration-specialist'
);

-- ============================================================
-- SPECIALIZED AGENT LAYER - TRANSACTION WORKFLOW AGENTS (DevForge AI)
-- ============================================================

-- 7. Transaction Processor (Ledger)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'DevForge AI'),
  'devforge-ai-transaction-processor',
  'specialist',
  'Transaction Processor',
  '📊',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Order processing and approval chain management; Transaction workflow orchestration; Financial data validation; Transaction status tracking; Multi-party coordination and approval routing.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.2,
    "max_tokens": 4096,
    "skills": ["order-processing", "approval-chain-management", "transaction-orchestration", "financial-validation", "status-tracking", "multi-party-coordination", "approval-routing", "transaction-auditing"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 10,
    "timeout_seconds": 720,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": true
    }
  }'::jsonb,
  450000,
  0,
  '{
    "execute": {
      "automation_engine": "transaction_processor",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "process": {
      "financial_transactions": true,
      "approval_chains": true,
      "order_processing": true
    },
    "access": {
      "read_transaction_data": true,
      "write_transaction_logs": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Ledger",
    "specialization": "transaction-processing",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "transaction-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'devforge-ai-transaction-processor'
);

-- 8. Financial Validator (Audit)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'DevForge AI'),
  'devforge-ai-financial-validator',
  'specialist',
  'Financial Validator',
  '💰',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Budget and compliance validation; Financial rule enforcement; Transaction compliance checking; Financial risk assessment; Regulatory requirement validation and audit trail management.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.1,
    "max_tokens": 3072,
    "skills": ["budget-validation", "compliance-checking", "financial-rule-enforcement", "risk-assessment", "regulatory-validation", "audit-trail-management", "financial-compliance", "transaction-validation"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 8,
    "timeout_seconds": 600,
    "retry_attempts": 1,
    "error_handling": {
      "auto_retry": false,
      "escalation_enabled": true
    }
  }'::jsonb,
  500000,
  0,
  '{
    "execute": {
      "automation_engine": "financial_validator",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "validate": {
      "financial_compliance": true,
      "budget_constraints": true,
      "regulatory_requirements": true
    },
    "access": {
      "read_financial_data": true,
      "write_validation_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Audit",
    "specialization": "financial-validation",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "transaction-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'devforge-ai-financial-validator'
);

-- 9. Multi-Discipline Coordinator (Bridge)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'DevForge AI'),
  'devforge-ai-multi-discipline-coordinator',
  'specialist',
  'Multi-Discipline Coordinator',
  '🌉',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Technical team coordination across disciplines; Cross-functional collaboration management; Resource allocation and scheduling; Dependency management and milestone tracking; Communication facilitation between technical teams.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.4,
    "max_tokens": 4096,
    "skills": ["technical-team-coordination", "cross-functional-collaboration", "resource-allocation", "dependency-management", "milestone-tracking", "communication-facilitation", "schedule-optimization", "conflict-resolution"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 12,
    "timeout_seconds": 900,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": true
    }
  }'::jsonb,
  400000,
  0,
  '{
    "execute": {
      "automation_engine": "coordinator",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "coordinate": {
      "technical_teams": true,
      "cross_functional_projects": true,
      "resource_allocation": true
    },
    "access": {
      "read_project_data": true,
      "write_coordination_logs": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Bridge",
    "specialization": "multi-discipline-coordination",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "transaction-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'devforge-ai-multi-discipline-coordinator'
);

-- 10. Document Generation Specialist (Scribe)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'DevForge AI'),
  'devforge-ai-document-generation-specialist',
  'specialist',
  'Document Generation Specialist',
  '📝',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Template-based document creation; Dynamic content generation; Document formatting and styling; Multi-format document output; Template management and version control; Content validation and quality assurance.',
  'hermes_local',
  '{
    "model": "anthropic/claude-haiku-3.5",
    "temperature": 0.3,
    "max_tokens": 2048,
    "skills": ["template-based-generation", "dynamic-content-creation", "document-formatting", "multi-format-output", "template-management", "version-control", "content-validation", "quality-assurance"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 18,
    "timeout_seconds": 360,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": false
    }
  }'::jsonb,
  300000,
  0,
  '{
    "execute": {
      "automation_engine": "document_generator",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "generate": {
      "transaction_documents": true,
      "contract_templates": true,
      "report_generation": true
    },
    "access": {
      "read_template_data": true,
      "write_generated_documents": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Scribe",
    "specialization": "document-generation",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "transaction-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'devforge-ai-document-generation-specialist'
);

-- ============================================================
-- SPECIALIZED AGENT LAYER - QUALIFICATION WORKFLOW AGENTS (QualityForge AI)
-- ============================================================

-- 11. Assessment Criteria Manager (Judge)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'QualityForge AI'),
  'qualityforge-ai-assessment-criteria-manager',
  'specialist',
  'Assessment Criteria Manager',
  '⚖️',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Automated evaluation framework development; Multi-criteria assessment management; Evaluation criteria standardization; Assessment template creation; Criteria validation and calibration; Performance benchmarking.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.2,
    "max_tokens": 3072,
    "skills": ["automated-evaluation-framework", "multi-criteria-assessment", "evaluation-standardization", "assessment-template-creation", "criteria-validation", "calibration-management", "performance-benchmarking", "quality-metrics"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 8,
    "timeout_seconds": 600,
    "retry_attempts": 1,
    "error_handling": {
      "auto_retry": false,
      "escalation_enabled": true
    }
  }'::jsonb,
  400000,
  0,
  '{
    "execute": {
      "automation_engine": "assessment_manager",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "manage": {
      "assessment_criteria": true,
      "evaluation_frameworks": true,
      "quality_standards": true
    },
    "access": {
      "read_assessment_data": true,
      "write_evaluation_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Judge",
    "specialization": "assessment-criteria-management",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "qualification-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'qualityforge-ai-assessment-criteria-manager'
);

-- 12. Compliance Validator (Sentinel)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'QualityForge AI'),
  'qualityforge-ai-compliance-validator',
  'specialist',
  'Compliance Validator',
  '🛡️',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Regulatory and standards checking; Compliance verification; Safety requirement validation; Documentation compliance assessment; Audit trail management; Regulatory change tracking.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.1,
    "max_tokens": 4096,
    "skills": ["regulatory-checking", "standards-validation", "compliance-verification", "safety-requirements", "documentation-assessment", "audit-trail-management", "regulatory-tracking", "certification-validation"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 6,
    "timeout_seconds": 900,
    "retry_attempts": 1,
    "error_handling": {
      "auto_retry": false,
      "escalation_enabled": true
    }
  }'::jsonb,
  500000,
  0,
  '{
    "execute": {
      "automation_engine": "compliance_validator",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "validate": {
      "regulatory_compliance": true,
      "safety_standards": true,
      "certification_requirements": true
    },
    "access": {
      "read_compliance_data": true,
      "write_validation_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Sentinel",
    "specialization": "compliance-validation",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "qualification-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'qualityforge-ai-compliance-validator'
);

-- 13. Documentation Processor (Archivist)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'QualityForge AI'),
  'qualityforge-ai-documentation-processor',
  'specialist',
  'Documentation Processor',
  '📚',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'File analysis and verification; Document authenticity checking; Documentation completeness assessment; Record management and archiving; Document security and access control; Version control and change tracking.',
  'hermes_local',
  '{
    "model": "anthropic/claude-haiku-3.5",
    "temperature": 0.2,
    "max_tokens": 2048,
    "skills": ["file-analysis", "document-verification", "authenticity-checking", "completeness-assessment", "record-management", "archiving-specialist", "document-security", "version-control"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 15,
    "timeout_seconds": 480,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": false
    }
  }'::jsonb,
  350000,
  0,
  '{
    "execute": {
      "automation_engine": "documentation_processor",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "process": {
      "documentation_files": true,
      "record_management": true,
      "archiving_operations": true
    },
    "access": {
      "read_documentation_data": true,
      "write_processing_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Archivist",
    "specialization": "documentation-processing",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "qualification-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'qualityforge-ai-documentation-processor'
);

-- 14. Decision Support Specialist (Oracle)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'QualityForge AI'),
  'qualityforge-ai-decision-support-specialist',
  'specialist',
  'Decision Support Specialist',
  '🔮',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Recommendation and ranking systems; Automated evaluation scoring; Decision support analytics; Risk assessment and mitigation; Performance prediction and forecasting; Alternative scenario analysis.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.3,
    "max_tokens": 3072,
    "skills": ["recommendation-systems", "automated-scoring", "decision-analytics", "risk-assessment", "performance-prediction", "scenario-analysis", "ranking-algorithms", "decision-optimization"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 10,
    "timeout_seconds": 720,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": true
    }
  }'::jsonb,
  450000,
  0,
  '{
    "execute": {
      "automation_engine": "decision_support",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "support": {
      "decision_making": true,
      "risk_assessment": true,
      "performance_analysis": true
    },
    "access": {
      "read_decision_data": true,
      "write_recommendation_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Oracle",
    "specialization": "decision-support",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "qualification-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'qualityforge-ai-decision-support-specialist'
);

-- ============================================================
-- SPECIALIZED AGENT LAYER - DOCUMENT PROCESSING WORKFLOW AGENTS (KnowledgeForge AI)
-- ============================================================

-- 15. Content Extractor (Miner)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'KnowledgeForge AI'),
  'knowledgeforge-ai-content-extractor',
  'specialist',
  'Content Extractor',
  '⛏️',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Multi-format document parsing; Content structure analysis; Information extraction and categorization; Data normalization and standardization; Content quality assessment; Metadata generation and tagging.',
  'hermes_local',
  '{
    "model": "anthropic/claude-haiku-3.5",
    "temperature": 0.2,
    "max_tokens": 2048,
    "skills": ["multi-format-parsing", "content-structure-analysis", "information-extraction", "data-normalization", "content-quality-assessment", "metadata-generation", "tagging-systems", "categorization-algorithms"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 20,
    "timeout_seconds": 360,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": false
    }
  }'::jsonb,
  300000,
  0,
  '{
    "execute": {
      "automation_engine": "content_extractor",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "extract": {
      "document_content": true,
      "structured_data": true,
      "metadata_information": true
    },
    "access": {
      "read_document_content": true,
      "write_extraction_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Miner",
    "specialization": "content-extraction",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "document-processing-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'knowledgeforge-ai-content-extractor'
);

-- 16. Analysis Engine (Analyst)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'KnowledgeForge AI'),
  'knowledgeforge-ai-analysis-engine',
  'specialist',
  'Analysis Engine',
  '🔍',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Skills and competency evaluation; Content analysis and interpretation; Pattern recognition in documents; Knowledge graph construction; Semantic analysis and understanding; Content relevance assessment.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.3,
    "max_tokens": 4096,
    "skills": ["skills-evaluation", "competency-analysis", "content-interpretation", "pattern-recognition", "knowledge-graph-construction", "semantic-analysis", "relevance-assessment", "content-understanding"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 12,
    "timeout_seconds": 600,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": true
    }
  }'::jsonb,
  450000,
  0,
  '{
    "execute": {
      "automation_engine": "analysis_engine",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "analyze": {
      "document_content": true,
      "skills_competencies": true,
      "knowledge_patterns": true
    },
    "access": {
      "read_analysis_data": true,
      "write_analysis_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Analyst",
    "specialization": "content-analysis",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "document-processing-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'knowledgeforge-ai-analysis-engine'
);

-- 17. Classification Specialist (Sorter)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'KnowledgeForge AI'),
  'knowledgeforge-ai-classification-specialist',
  'specialist',
  'Classification Specialist',
  '📂',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Document type identification and routing; Content categorization and tagging; Classification model training; Taxonomy management and maintenance; Classification accuracy validation; Routing rule optimization.',
  'hermes_local',
  '{
    "model": "anthropic/claude-haiku-3.5",
    "temperature": 0.2,
    "max_tokens": 1536,
    "skills": ["document-type-identification", "content-categorization", "classification-model-training", "taxonomy-management", "classification-validation", "routing-optimization", "tagging-systems", "category-maintenance"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 25,
    "timeout_seconds": 240,
    "retry_attempts": 3,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": false
    }
  }'::jsonb,
  350000,
  0,
  '{
    "execute": {
      "automation_engine": "classification_specialist",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "classify": {
      "document_types": true,
      "content_categories": true,
      "routing_decisions": true
    },
    "access": {
      "read_classification_data": true,
      "write_routing_decisions": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Sorter",
    "specialization": "document-classification",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "document-processing-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'knowledgeforge-ai-classification-specialist'
);

-- 18. Ranking Algorithm Specialist (Ranker)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'KnowledgeForge AI'),
  'knowledgeforge-ai-ranking-algorithm-specialist',
  'specialist',
  'Ranking Algorithm Specialist',
  '🏆',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Automated prioritization systems; Ranking model development and optimization; Scoring algorithm calibration; Performance metric analysis; Ranking criteria customization; Algorithm performance monitoring and improvement.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.3,
    "max_tokens": 3072,
    "skills": ["automated-prioritization", "ranking-model-development", "scoring-algorithm-calibration", "performance-metric-analysis", "ranking-criteria-customization", "algorithm-monitoring", "ranking-optimization", "performance-improvement"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 15,
    "timeout_seconds": 480,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": true
    }
  }'::jsonb,
  400000,
  0,
  '{
    "execute": {
      "automation_engine": "ranking_specialist",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "rank": {
      "content_priorities": true,
      "scoring_algorithms": true,
      "performance_metrics": true
    },
    "access": {
      "read_ranking_data": true,
      "write_ranking_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Ranker",
    "specialization": "ranking-algorithms",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "document-processing-workflow",
    "layer": "specialized"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'knowledgeforge-ai-ranking-algorithm-specialist'
);

-- ============================================================
-- SUPPORT LAYER - UI/UX AND INTEGRATION
-- ============================================================

-- 19. Workflow UX Designer (Harmony - ContentForge AI)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'ContentForge AI'),
  'contentforge-ai-workflow-ux-designer',
  'specialist',
  'Workflow UX Designer',
  '🎨',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Cross-workflow interface standardization; Adaptive UI pattern generation; User interaction analysis and optimization; Accessibility and usability validation; Workflow visualization design; User experience research and testing.',
  'hermes_local',
  '{
    "model": "anthropic/claude-haiku-3.5",
    "temperature": 0.5,
    "max_tokens": 2048,
    "skills": ["interface-standardization", "adaptive-ui-generation", "user-interaction-analysis", "accessibility-validation", "workflow-visualization", "ux-research", "usability-testing", "design-optimization"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 10,
    "timeout_seconds": 600,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": false
    }
  }'::jsonb,
  400000,
  0,
  '{
    "execute": {
      "automation_engine": "ux_designer",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "design": {
      "workflow_interfaces": true,
      "user_experiences": true,
      "visualization_systems": true
    },
    "access": {
      "read_ux_data": true,
      "write_design_specifications": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Designer",
    "specialization": "workflow-ux-design",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "support-layer",
    "layer": "support"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'contentforge-ai-workflow-ux-designer'
);

-- ============================================================
-- INTEGRATION AGENTS (InfraForge AI)
-- ============================================================

-- 20. API Integration Specialist (Link)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'InfraForge AI'),
  'infraforge-ai-api-integration-specialist',
  'specialist',
  'API Integration Specialist',
  '🔗',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'External system connectivity; API endpoint management; Data exchange protocols; Integration testing and validation; API security and authentication; Performance monitoring and optimization.',
  'hermes_local',
  '{
    "model": "anthropic/claude-haiku-3.5",
    "temperature": 0.2,
    "max_tokens": 2048,
    "skills": ["external-system-connectivity", "api-endpoint-management", "data-exchange-protocols", "integration-testing", "api-security", "authentication-management", "performance-monitoring", "optimization-specialist"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 15,
    "timeout_seconds": 480,
    "retry_attempts": 3,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": true
    }
  }'::jsonb,
  450000,
  0,
  '{
    "execute": {
      "automation_engine": "api_integration",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "integrate": {
      "external_systems": true,
      "api_endpoints": true,
      "data_exchanges": true
    },
    "access": {
      "read_integration_data": true,
      "write_connection_logs": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Link",
    "specialization": "api-integration",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "integration-agents",
    "layer": "integration"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'infraforge-ai-api-integration-specialist'
);

-- 21. Data Synchronization Manager (Sync)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'InfraForge AI'),
  'infraforge-ai-data-synchronization-manager',
  'specialist',
  'Data Synchronization Manager',
  '🔄',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Cross-platform data management; Data synchronization protocols; Conflict resolution and merging; Data consistency validation; Synchronization scheduling and monitoring; Data transformation and mapping.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.2,
    "max_tokens": 3072,
    "skills": ["cross-platform-data-management", "synchronization-protocols", "conflict-resolution", "data-consistency-validation", "sync-scheduling", "monitoring-systems", "data-transformation", "mapping-algorithms"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 12,
    "timeout_seconds": 720,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": true
    }
  }'::jsonb,
  500000,
  0,
  '{
    "execute": {
      "automation_engine": "data_sync_manager",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "synchronize": {
      "cross_platform_data": true,
      "data_consistency": true,
      "conflict_resolution": true
    },
    "access": {
      "read_sync_data": true,
      "write_sync_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Sync",
    "specialization": "data-synchronization",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "integration-agents",
    "layer": "integration"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'infraforge-ai-data-synchronization-manager'
);

-- 22. Security and Compliance Monitor (Guardian)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'InfraForge AI'),
  'infraforge-ai-security-compliance-monitor',
  'specialist',
  'Security and Compliance Monitor',
  '⚔️',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'Regulatory requirement validation; Security monitoring and alerting; Compliance auditing and reporting; Risk assessment and mitigation; Security policy enforcement; Incident detection and response.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.1,
    "max_tokens": 4096,
    "skills": ["regulatory-validation", "security-monitoring", "compliance-auditing", "risk-assessment", "security-policy-enforcement", "incident-detection", "response-coordination", "audit-reporting"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 8,
    "timeout_seconds": 900,
    "retry_attempts": 1,
    "error_handling": {
      "auto_retry": false,
      "escalation_enabled": true
    }
  }'::jsonb,
  600000,
  0,
  '{
    "execute": {
      "automation_engine": "security_monitor",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "monitor": {
      "security_compliance": true,
      "regulatory_requirements": true,
      "risk_assessment": true
    },
    "access": {
      "read_security_data": true,
      "write_compliance_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Guardian",
    "specialization": "security-compliance-monitoring",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "integration-agents",
    "layer": "integration"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'infraforge-ai-security-compliance-monitor'
);

-- 23. Performance Optimization Specialist (Turbo)
INSERT INTO agents (
  id,
  company_id,
  name,
  role,
  title,
  icon,
  status,
  reports_to,
  capabilities,
  adapter_type,
  adapter_config,
  runtime_config,
  budget_monthly_cents,
  spent_monthly_cents,
  permissions,
  metadata,
  created_at,
  updated_at
)
SELECT
  gen_random_uuid(),
  (SELECT id FROM companies WHERE name = 'InfraForge AI'),
  'infraforge-ai-performance-optimization-specialist',
  'specialist',
  'Performance Optimization Specialist',
  '🚀',
  'idle',
  NULL,  -- Reports to operations director - set to NULL until director is registered
  'System efficiency improvements; Performance bottleneck identification; Resource utilization optimization; Scalability enhancement; Performance monitoring and alerting; Optimization strategy development and implementation.',
  'hermes_local',
  '{
    "model": "anthropic/claude-sonnet-3.5",
    "temperature": 0.3,
    "max_tokens": 3072,
    "skills": ["system-efficiency-improvements", "bottleneck-identification", "resource-utilization-optimization", "scalability-enhancement", "performance-monitoring", "alerting-systems", "optimization-strategy", "performance-analysis"]
  }'::jsonb,
  '{
    "max_concurrent_tasks": 10,
    "timeout_seconds": 600,
    "retry_attempts": 2,
    "error_handling": {
      "auto_retry": true,
      "escalation_enabled": true
    }
  }'::jsonb,
  550000,
  0,
  '{
    "execute": {
      "automation_engine": "performance_optimizer",
      "allowed_domains": ["docs-paperclip", "docs-construct-ai"]
    },
    "optimize": {
      "system_performance": true,
      "resource_utilization": true,
      "scalability_improvements": true
    },
    "access": {
      "read_performance_data": true,
      "write_optimization_reports": true,
      "admin_functions": false
    }
  }'::jsonb,
  '{
    "human_name": "Turbo",
    "specialization": "performance-optimization",
    "created_via": "ATLAS-WORKFLOW-ARCHITECTURE",
    "department": "integration-agents",
    "layer": "integration"
  }'::jsonb,
  NOW(),
  NOW()
WHERE NOT EXISTS (
  SELECT 1 FROM agents WHERE name = 'infraforge-ai-performance-optimization-specialist'
);

-- ============================================================
-- VERIFICATION QUERIES
-- ============================================================

-- Check all agents were created
-- SELECT name, title, status, adapter_config->>'model' as model
-- FROM agents
-- WHERE name LIKE '%workflow-%'
-- ORDER BY name;

-- Count agents by company
-- SELECT c.name as company, COUNT(a.id) as agent_count
-- FROM companies c
-- LEFT JOIN agents a ON c.id = a.company_id
-- WHERE a.name LIKE '%workflow-%'
-- GROUP BY c.name
-- ORDER BY agent_count DESC;

-- ============================================================
-- ROLLBACK (if needed - use with caution)
-- ============================================================
-- DELETE FROM agents WHERE name LIKE '%workflow-%' AND metadata->>'created_via' = 'ATLAS-WORKFLOW-ARCHITECTURE';